services:
  my_service:
    # build: path
    image: frostlab/holoros:latest
    container_name: holoocean
    user: ue4
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    privileged: true