/**:
  ros_parameters:
    holoocean_scenario:
      name: hovering_dynamics
      package_name: Ocean   
      world: OpenWater
      main_agent: auv0      
      ticks_per_sec: 30
      frames_per_sec: 180
      draw_arrow: true
      show_viewport: true
      agents:
        - agent_name: auv0
          agent_type: TorpedoAUV
          control_scheme: 1  
          location: [0, 0, -270]
          rotation: [0, 0, 90]
          publish_commands: true
          sensors:
            - sensor_type: DynamicsSensor
              configuration:
                UseCOM: true
                UseRPY: false
              ros_publish: true
            - sensor_type: DVLSensor
              ros_publish: true
              tick_every: 3
              configuration:
                VelCov: [0.001, 0.001, 0.001, 0.001]
            - sensor_type: IMUSensor
              ros_publish: true
              tick_every: 3
              configuration:
                AccelCov: [0.001, 0.001, 0.001]
                AngVelCov: [0.001, 0.001, 0.001]
            - sensor_type: GPSSensor
              ros_publish: true
              tick_every: 30
              configuration:
                Cov: [0.0001, 0.0001, 0.0001]
                Depth: 1.5
                DepthCov: 0.05
            - sensor_type: LocationSensor
              ros_publish: true
            - sensor_type: RotationSensor
              ros_publish: true
            - sensor_type: DepthSensor
              tick_every: 5
              ros_publish: true
              configuration:
                Sigma: 0.001
            - sensor_type: VelocitySensor
              ros_publish: true
            # - sensor_type: SidescanSonar
            #   ros_publish: false
            #   conifguration:
            #     ViewRegion: true
          dynamics: 
            mass: 16
            length: 1.6
            rho: 1026
            diam: 0.19
            r_bg: [0, 0, 0.02]
            r_bb: [0, 0, 0]
            Cd: 0.42
            # K_nomoto:  
          actuator: 
            fin_area: 0.00665
            deltaMax_fin_deg: 25
            nMax: 1525
          autopilot: 
            depth:
              wn_d_z: 0.2
              Kp_z: 0.5
              T_z: 100
              Kp_theta: 4.0
              Kd_theta: 2.3 #2.3
              Ki_theta: 0.6 #0.6
              K_w: 5.0
              theta_max_deg: 30
            heading:
              wn_d: 0.2
              zeta_d: 0.8
              r_max: 0.9
              lam: 0.1
              phi_b: 0.1
              K_d: 0.0 #0.5
              K_sigma: 0.05
            surge:
              kp_surge: 700.0
              ki_surge: 0.0 #100.0
              kd_surge: 0.0 #40.0
    
/controller_node:
  ros_parameters:
    torpedo_fin: 3
    vehicle_name: auv0

/command_node:
  ros_parameters:
    random: false
