holoocean:
  holoocean_node:
    ros__parameters:
      draw_arrow: false
      show_viewport: true
      relative_path: true
      scenario_path: 'config/torpedo_fossen.json'
      publish_commands: true
      map_frame: 'holoocean_map'
      # render_quality: 0
      
